USE hr_db;


-- 1.
SELECT EMPLOYEE_ID, SUBSTR(EMAIL, 1, LENGTH(EMAIL-3)) FROM employees;
-- or:
SELECT EMPLOYEE_ID, REVERSE(SUBSTR(REVERSE(EMAIL), 4)) FROM employees;

-- 2.
SELECT * FROM locations WHERE LENGTH(STREET_ADDRESS) =
(SELECT MIN(LENGTH(STREET_ADDRESS)) FROM locations);

-- 3.
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM employees
WHERE
(
	SUBSTR(FIRST_NAME, 1, 1) = 'A'
    OR
    SUBSTR(FIRST_NAME, 1, 1) = 'J'
    OR
    SUBSTR(FIRST_NAME, 1, 1) = 'M'
)
GROUP BY FIRST_NAME;
